from PySide6.QtCore import QObject as QObject
from PySide6.QtGui import QWindow as QWindow
from PySide6.QtQml import QPyQmlParserStatus
from PySide6.QtQuick import QQuickItem

QML_IMPORT_NAME: str
QML_IMPORT_MAJOR_VERSION: int

class HusWindowAgent(QPyQmlParserStatus):
    def __init__(self, parent: QObject = None) -> None: ...
    def classBegin(self) -> None: ...
    def componentComplete(self) -> None: ...
    def setTitleBar(self, item: QQuickItem) -> bool: ...
    def setSystemButton(self, button: int, item: QQuickItem) -> bool: ...
    def setHitTestVisible(self, item: QQuickItem, visible: bool) -> bool: ...
    def setWindowAttribute(self, attribute: str, value: bool) -> bool: ...
