from collections.abc import Sequence

class QrCode:
    @staticmethod
    def encode_text(text: str, ecl: QrCode.Ecc) -> QrCode: ...
    @staticmethod
    def encode_binary(data: bytes | Sequence[int], ecl: QrCode.Ecc) -> QrCode: ...
    @staticmethod
    def encode_segments(segs: Sequence[QrSegment], ecl: QrCode.Ecc, minversion: int = 1, maxversion: int = 40, mask: int = -1, boostecl: bool = True) -> QrCode: ...
    def __init__(self, version: int, errcorlvl: QrCode.Ecc, datacodewords: bytes | Sequence[int], msk: int) -> None: ...
    def get_version(self) -> int: ...
    def get_size(self) -> int: ...
    def get_error_correction_level(self) -> QrCode.Ecc: ...
    def get_mask(self) -> int: ...
    def get_module(self, x: int, y: int) -> bool: ...
    MIN_VERSION: int
    MAX_VERSION: int
    class Ecc:
        ordinal: int
        formatbits: int
        def __init__(self, i: int, fb: int) -> None: ...
        LOW: QrCode.Ecc
        MEDIUM: QrCode.Ecc
        QUARTILE: QrCode.Ecc
        HIGH: QrCode.Ecc

class QrSegment:
    @staticmethod
    def make_bytes(data: bytes | Sequence[int]) -> QrSegment: ...
    @staticmethod
    def make_numeric(digits: str) -> QrSegment: ...
    @staticmethod
    def make_alphanumeric(text: str) -> QrSegment: ...
    @staticmethod
    def make_segments(text: str) -> list[QrSegment]: ...
    @staticmethod
    def make_eci(assignval: int) -> QrSegment: ...
    @staticmethod
    def is_numeric(text: str) -> bool: ...
    @staticmethod
    def is_alphanumeric(text: str) -> bool: ...
    def __init__(self, mode: QrSegment.Mode, numch: int, bitdata: Sequence[int]) -> None: ...
    def get_mode(self) -> QrSegment.Mode: ...
    def get_num_chars(self) -> int: ...
    def get_data(self) -> list[int]: ...
    @staticmethod
    def get_total_bits(segs: Sequence[QrSegment], version: int) -> int | None: ...
    class Mode:
        def __init__(self, modebits: int, charcounts: tuple[int, int, int]) -> None: ...
        def get_mode_bits(self) -> int: ...
        def num_char_count_bits(self, ver: int) -> int: ...
        NUMERIC: QrSegment.Mode
        ALPHANUMERIC: QrSegment.Mode
        BYTE: QrSegment.Mode
        KANJI: QrSegment.Mode
        ECI: QrSegment.Mode

class _BitBuffer(list[int]):
    def append_bits(self, val: int, n: int) -> None: ...

class DataTooLongError(ValueError): ...
