from .huscolorgenerator import HusColorGenerator as HusColorGenerator
from .husradiusgenerator import HusRadiusGenerator as HusRadiusGenerator
from .hussizegenerator import HusSizeGenerator as HusSizeGenerator
from PySide6.QtCore import QObject
from PySide6.QtGui import QColor

QML_IMPORT_NAME: str
QML_IMPORT_MAJOR_VERSION: int

class HusThemeFunctions(QObject):
    def __init__(self, parent=None) -> None: ...
    @staticmethod
    def genColor(color: int | QColor, light: bool = True, background: QColor = ...) -> list[QColor]: ...
    @staticmethod
    def genColorString(color: QColor, light: bool = True, background: QColor = ...) -> list[str]: ...
    @staticmethod
    def genFontSize(font_size_base: float) -> list[float]: ...
    @staticmethod
    def genFontLineHeight(font_size_base: float) -> list[float]: ...
    @staticmethod
    def genRadius(radius_base: int) -> list[int]: ...
    @staticmethod
    def genFontFamily(family_base: str) -> str: ...
    @staticmethod
    def darker(color: QColor, factor: int = 140) -> QColor: ...
    @staticmethod
    def lighter(color: QColor, factor: int = 140) -> QColor: ...
    @staticmethod
    def alpha(color: QColor, alpha_val: float = 0.5) -> QColor: ...
    @staticmethod
    def onBackground(color: QColor, background: QColor) -> QColor: ...
    @staticmethod
    def multiply(num1: float, num2: float) -> float: ...
