from .huscolorgenerator import HusColorGenerator as HusColorGenerator
from .hussystemthemehelper import HusSystemThemeHelper as HusSystemThemeHelper
from .husthemefunctions import HusThemeFunctions as HusThemeFunctions
from PySide6.QtCore import QObject
from PySide6.QtGui import QColor
from _typeshed import Incomplete
from dataclasses import dataclass, field
from enum import Enum

QML_IMPORT_NAME: str
QML_IMPORT_MAJOR_VERSION: int

class Component(Enum):
    HusButton = 'HusButton'
    HusIconText = 'HusIconText'
    HusCopyableText = 'HusCopyableText'
    HusCaptionButton = 'HusCaptionButton'
    HusTour = 'HusTour'
    HusMenu = 'HusMenu'
    HusDivider = 'HusDivider'
    HusEmpty = 'HusEmpty'
    HusSwitch = 'HusSwitch'
    HusScrollBar = 'HusScrollBar'
    HusSlider = 'HusSlider'
    HusTabView = 'HusTabView'
    HusToolTip = 'HusToolTip'
    HusSelect = 'HusSelect'
    HusInput = 'HusInput'
    HusRate = 'HusRate'
    HusRadio = 'HusRadio'
    HusCheckBox = 'HusCheckBox'
    HusDrawer = 'HusDrawer'
    HusCollapse = 'HusCollapse'
    HusCard = 'HusCard'
    HusPagination = 'HusPagination'
    HusPopup = 'HusPopup'
    HusTimeline = 'HusTimeline'
    HusTag = 'HusTag'
    HusTableView = 'HusTableView'
    HusMessage = 'HusMessage'
    HusAutoComplete = 'HusAutoComplete'
    HusProgress = 'HusProgress'
    HusCarousel = 'HusCarousel'
    HusBreadcrumb = 'HusBreadcrumb'
    HusImage = 'HusImage'
    HusMultiSelect = 'HusMultiSelect'
    HusDateTimePicker = 'HusDateTimePicker'
    HusNotification = 'HusNotification'
    HusPopconfirm = 'HusPopconfirm'
    HusPopover = 'HusPopover'
    HusModal = 'HusModal'
    HusTextArea = 'HusTextArea'
    HusSpin = 'HusSpin'

@dataclass
class ComponentData:
    path: str = ...
    token_map: dict = field(default_factory=dict)
    install_token_map: dict[str, str] = field(default_factory=dict)

@dataclass
class ThemeData:
    theme_object: QObject = ...
    component_map: dict[str, ComponentData] = field(default_factory=dict)

class HusTheme(QObject):
    class DarkMode(Enum):
        Light = 0
        Dark = 1
        System = 2
    class TextRenderType(Enum):
        QtRendering = 0
        NativeRendering = 1
        CurveRendering = 2
    isDarkChanged: Incomplete
    darkModeChanged: Incomplete
    textRenderTypeChanged: Incomplete
    sizeHintChanged: Incomplete
    animationEnabledChanged: Incomplete
    PrimaryChanged: Incomplete
    HusButtonChanged: Incomplete
    HusIconTextChanged: Incomplete
    HusCopyableTextChanged: Incomplete
    HusCaptionButtonChanged: Incomplete
    HusTourChanged: Incomplete
    HusMenuChanged: Incomplete
    HusDividerChanged: Incomplete
    HusEmptyChanged: Incomplete
    HusSwitchChanged: Incomplete
    HusScrollBarChanged: Incomplete
    HusSliderChanged: Incomplete
    HusTabViewChanged: Incomplete
    HusToolTipChanged: Incomplete
    HusSelectChanged: Incomplete
    HusInputChanged: Incomplete
    HusRateChanged: Incomplete
    HusRadioChanged: Incomplete
    HusCheckBoxChanged: Incomplete
    HusDrawerChanged: Incomplete
    HusCollapseChanged: Incomplete
    HusCardChanged: Incomplete
    HusPaginationChanged: Incomplete
    HusPopupChanged: Incomplete
    HusTimelineChanged: Incomplete
    HusTagChanged: Incomplete
    HusTableViewChanged: Incomplete
    HusMessageChanged: Incomplete
    HusAutoCompleteChanged: Incomplete
    HusProgressChanged: Incomplete
    HusCarouselChanged: Incomplete
    HusBreadcrumbChanged: Incomplete
    HusImageChanged: Incomplete
    HusMultiSelectChanged: Incomplete
    HusDateTimePickerChanged: Incomplete
    HusNotificationChanged: Incomplete
    HusPopconfirmChanged: Incomplete
    HusPopoverChanged: Incomplete
    HusModalChanged: Incomplete
    HusTextAreaChanged: Incomplete
    HusSpinChanged: Incomplete
    def __init__(self, parent=None) -> None: ...
    def isDark(self) -> bool: ...
    def sizeHint(self) -> dict[str, float]: ...
    def Primary(self) -> dict: ...
    def HusButton(self) -> dict: ...
    def HusIconText(self) -> dict: ...
    def HusCopyableText(self) -> dict: ...
    def HusCaptionButton(self) -> dict: ...
    def HusTour(self) -> dict: ...
    def HusMenu(self) -> dict: ...
    def HusDivider(self) -> dict: ...
    def HusEmpty(self) -> dict: ...
    def HusSwitch(self) -> dict: ...
    def HusScrollBar(self) -> dict: ...
    def HusSlider(self) -> dict: ...
    def HusTabView(self) -> dict: ...
    def HusToolTip(self) -> dict: ...
    def HusSelect(self) -> dict: ...
    def HusInput(self) -> dict: ...
    def HusRate(self) -> dict: ...
    def HusRadio(self) -> dict: ...
    def HusCheckBox(self) -> dict: ...
    def HusDrawer(self) -> dict: ...
    def HusCollapse(self) -> dict: ...
    def HusCard(self) -> dict: ...
    def HusPagination(self) -> dict: ...
    def HusPopup(self) -> dict: ...
    def HusTimeline(self) -> dict: ...
    def HusTag(self) -> dict: ...
    def HusTableView(self) -> dict: ...
    def HusMessage(self) -> dict: ...
    def HusAutoComplete(self) -> dict: ...
    def HusProgress(self) -> dict: ...
    def HusCarousel(self) -> dict: ...
    def HusBreadcrumb(self) -> dict: ...
    def HusImage(self) -> dict: ...
    def HusMultiSelect(self) -> dict: ...
    def HusDateTimePicker(self) -> dict: ...
    def HusNotification(self) -> dict: ...
    def HusPopconfirm(self) -> dict: ...
    def HusPopover(self) -> dict: ...
    def HusModal(self) -> dict: ...
    def HusTextArea(self) -> dict: ...
    def HusSpin(self) -> dict: ...
    def registerCustomComponentTheme(self, theme_object: QObject, component: str, theme_map: dict, theme_path: str): ...
    def reloadTheme(self) -> None: ...
    def installThemeColorTextBase(self, light_and_dark: str): ...
    def installThemeColorBgBase(self, light_and_dark: str): ...
    def installThemePrimaryColorBase(self, color_base: QColor): ...
    def installThemePrimaryFontSizeBase(self, font_size_base: int): ...
    def installThemePrimaryFontFamiliesBase(self, families_base: str): ...
    def installThemePrimaryRadiusBase(self, radius_base: int): ...
    def installThemePrimaryAnimationBase(self, duration_fast: int, duration_mid: int, duration_slow: int): ...
    def installSizeHintRatio(self, size: str, ratio: float): ...
    def installIndexTheme(self, theme_path: str): ...
    def installIndexToken(self, token: str, value: str): ...
    def installComponentTheme(self, component: str, theme_path: str): ...
    def installComponentToken(self, component: str, token: str, value: str): ...
