from PySide6.QtCore import QDateTime, QObject, Qt as Qt
from PySide6.QtGui import QWindow
from _typeshed import Incomplete

user32: Incomplete
QML_IMPORT_NAME: str
QML_IMPORT_MAJOR_VERSION: int

class HusApi(QObject):
    def __init__(self, parent: QObject = None) -> None: ...
    def setWindowStaysOnTopHint(self, window: QWindow, hint: bool) -> None: ...
    def setWindowState(self, window: QWindow, state: int) -> None: ...
    def setPopupAllowAutoFlip(self, popup: QObject, allowVerticalFlip: bool = True, allowHorizontalFlip: bool = True) -> None: ...
    def getClipbordText(self) -> str: ...
    def setClipbordText(self, text: str) -> bool: ...
    def readFileToString(self, fileName: str) -> str: ...
    def getWeekNumber(self, dateTime: QDateTime) -> int: ...
    def dateFromString(self, dateTime: str, format: str) -> QDateTime: ...
    def openFile(self, fileName: str) -> None: ...
